-- Intencionalmente vazio desde a v0.3 (spec §6 e §10).
--
-- Este arquivo semeava a vida pessoal do autor: 15 categorias com exemplos de
-- estabelecimentos reais, três cartões nominais, renda, custos fixos e limites
-- de um mês específico. Um produto para distribuir não pode nascer com as
-- categorias de outra pessoa. O conteúdo está no histórico do git, e `card.md`
-- segue no repositório como documento histórico.
--
-- Editar este arquivo é seguro: o runner (src/infra/db.ts) registra migrações
-- por nome, sem checksum, e bancos existentes já a marcaram como aplicada — eles
-- nunca a re-executam. O seed genérico vive em 007_seed_defaults.sql.
SELECT 1;
